# Post Test 7 | Tensor Flow
#### Nama   : Novia Indah Ramadhani
#### NIM    : 2109106041
#### Kelas  : A2 2021

### Import Library

In [2]:
import tensorflow as tf
import numpy as np

### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor
- Membuat tensor dengan nilai random unifrom -> persebaran nilai tengahnya lebih banyak, dengan nilai min=1, max=25
- Mengganti tipe data menjadi int32 agar menyamakan tipe datanya = variabel prime_tensor

In [3]:
random_tensor = tf.random.uniform(shape = (5,5), minval=1, maxval=25, dtype=tf.int32)
random_tensor.numpy()
print(random_tensor)

tf.Tensor(
[[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]], shape=(5, 5), dtype=int32)


### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor
- Masukkan bilangan prima ke dalam list dengan shape 5,5
- Kemudia convert list tersebut ke dalam tensor menggunakan convert_to_tensor

In [5]:
list_prime = [[2, 3, 5, 7, 11], [17, 19, 23, 29, 31], [37, 41, 43, 47, 53], [59, 61, 67, 71, 73], [79, 83, 89, 97, 101]]
prime_tensor = tf.convert_to_tensor(list_prime)
prime_tensor.numpy()
print(prime_tensor)

tf.Tensor(
[[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]], shape=(5, 5), dtype=int32)


### Tampilkan dimensi dari kedua variable tersebut
Menampilkan dimensi menggunakan .shape

In [22]:
print(f'Display Dimensi Variabel random_tensor = {random_tensor.shape}')
print(f'Display Dimensi Variabel prime_tensor = {prime_tensor.shape}')

Display Dimensi Variabel random_tensor = (5, 5)
Display Dimensi Variabel prime_tensor = (5, 5)


### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

#### [1] ADD

In [28]:
jumlah = tf.add(random_tensor, prime_tensor)
jumlah.numpy()

print(f'Random Tensor = \n {random_tensor}')
print(f' Prime Tensor = \n {prime_tensor}')
print("========================================")
print(f' Hasil Random Tensor + Prime Tensor = \n {jumlah}')

Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Prime Tensor = 
 [[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]]
 Hasil Random Tensor + Prime Tensor = 
 [[ 21   4  12  29  27]
 [ 30  39  28  38  33]
 [ 54  65  52  58  55]
 [ 82  70  84  81  86]
 [ 88  84  98 104 109]]


#### [2] SUBTRACT

In [29]:
kurang = tf.subtract(random_tensor, prime_tensor)
kurang.numpy()

print(f'Random Tensor = \n {random_tensor}')
print(f' Prime Tensor = \n {prime_tensor}')
print("========================================")
print(f' Hasil Random Tensor - Prime Tensor = \n {kurang}')

Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Prime Tensor = 
 [[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]]
 Hasil Random Tensor - Prime Tensor = 
 [[ 17  -2   2  15   5]
 [ -4   1 -18 -20 -29]
 [-20 -17 -34 -36 -51]
 [-36 -52 -50 -61 -60]
 [-70 -82 -80 -90 -93]]


#### [3] MULTIPLY

In [30]:
kali = tf.multiply(random_tensor, prime_tensor)
kali.numpy()

print(f'Random Tensor = \n {random_tensor}')
print(f' Prime Tensor = \n {prime_tensor}')
print("========================================")
print(f' Hasil Random Tensor * Prime Tensor = \n {kali}')

Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Prime Tensor = 
 [[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]]
 Hasil Random Tensor * Prime Tensor = 
 [[  38    3   35  154  176]
 [ 221  380  115  261   62]
 [ 629  984  387  517  106]
 [1357  549 1139  710  949]
 [ 711   83  801  679  808]]


#### [4] DIVIDE

In [38]:
bagi = tf.divide(random_tensor, prime_tensor)
bagi.numpy()

print(f'Random Tensor = \n {random_tensor}')
print(f' Prime Tensor = \n {prime_tensor}')
print("==========================================================")
print(f' Hasil Random Tensor / Prime Tensor = \n {bagi}')

Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Prime Tensor = 
 [[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]]
 Hasil Random Tensor / Prime Tensor = 
 [[9.5        0.33333333 1.4        3.14285714 1.45454545]
 [0.76470588 1.05263158 0.2173913  0.31034483 0.06451613]
 [0.45945946 0.58536585 0.20930233 0.23404255 0.03773585]
 [0.38983051 0.14754098 0.25373134 0.14084507 0.17808219]
 [0.11392405 0.01204819 0.1011236  0.07216495 0.07920792]]


#### [5] POW

In [36]:
pangkat = tf.pow(random_tensor, prime_tensor)
pangkat.numpy()

print(f'Random Tensor = \n {random_tensor}')
print(f' Prime Tensor = \n {prime_tensor}')
print("===============================================================")
print(f' Hasil Random Tensor - Prime Tensor = \n {pangkat}')

Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Prime Tensor = 
 [[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]]
 Hasil Random Tensor - Prime Tensor = 
 [[        361           1       16807 -1800609408           0]
 [ 1645991757           0 -1883073043 -1635065239 -2147483648]
 [-1619706799           0 -1762824935  1874949219           0]
 [ 1671559623   945842025 -2134198479           0 -1232359763]
 [  740860601           1 -1537102391 -1837705465           0]]


### Tampilkan nilai maksimal dan minimal dari variable random_tensor
- Menampilkan nilai max dengan argmax()
- Menampilkan nilai min dengan argmin()

In [59]:
# Max
max_random_tensor = tf.argmax(random_tensor, axis=0)
print("Nilai Max random_tensor berdasarkan kolom :", max_random_tensor.numpy())

# Min
min_random_tensor = tf.argmin(random_tensor, axis=0)
print("Nilai Min random_tensor berdasarkan kolom :", min_random_tensor.numpy())

Nilai Max random_tensor berdasarkan kolom : [2 4 0 1 2]
Nilai Min random_tensor berdasarkan kolom : [3 1 4 0 0]


### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)
Menampilkan hasil dari penggabungan kedua variabel menggunakan .concat()

In [58]:
concat = tf.concat([random_tensor, prime_tensor], axis=1)
concat.numpy()

print(f'Random Tensor = \n {random_tensor}')
print(f' Prime Tensor = \n {prime_tensor}')
print("=========================================================")
print(f' Hasil Concat (Gabungan) Random Tensor & Prime Tensor = \n {concat}')

Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Prime Tensor = 
 [[  2   3   5   7  11]
 [ 17  19  23  29  31]
 [ 37  41  43  47  53]
 [ 59  61  67  71  73]
 [ 79  83  89  97 101]]
 Hasil Concat (Gabungan) Random Tensor & Prime Tensor = 
 [[ 19   1   7  22  16   2   3   5   7  11]
 [ 13  20   5   9   2  17  19  23  29  31]
 [ 17  24   9  11   2  37  41  43  47  53]
 [ 23   9  17  10  13  59  61  67  71  73]
 [  9   1   9   7   8  79  83  89  97 101]]


### Tampilkan hasil sorting dari kedua variable di atas. (descending)
Menampilkan sorting secara descending berdasarkan /barisnya menggunakan .sort()

In [57]:
print ("Descending Variabel random_tensor")
sort_rt = tf.sort(random_tensor, direction="DESCENDING")
sort_rt.numpy()

print(f'Random Tensor = \n {random_tensor}')
print("==============================")
print(f' Hasil Sorting Descending = \n {sort_rt}')

Descending Variabel random_tensor
Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Hasil Sorting Descending = 
 [[22 19 16  7  1]
 [20 13  9  5  2]
 [24 17 11  9  2]
 [23 17 13 10  9]
 [ 9  9  8  7  1]]


In [53]:
print ("Descending Variabel prime_tensor")
sort_pt = tf.sort(prime_tensor, direction="DESCENDING")
sort_pt.numpy()

print(f'Random Tensor = \n {random_tensor}')
print("=============================")
print(f' Hasil Sorting Descending = \n {sort_pt}')

Descending Variabel prime_tensor
Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Hasil Sorting Descending = 
 [[ 11   7   5   3   2]
 [ 31  29  23  19  17]
 [ 53  47  43  41  37]
 [ 73  71  67  61  59]
 [101  97  89  83  79]]


In [56]:
print ("Descending Gabungan Kedua Variabel (Concat)")
sort_concat =tf.sort(concat, direction="DESCENDING")
sort_concat.numpy()
print(f'Random Tensor = \n {random_tensor}')
print("=============================================")
print(f' Hasil Sorting Descending = \n {sort_concat}')

Descending Gabungan Kedua Variabel (Concat)
Random Tensor = 
 [[19  1  7 22 16]
 [13 20  5  9  2]
 [17 24  9 11  2]
 [23  9 17 10 13]
 [ 9  1  9  7  8]]
 Hasil Sorting Descending = 
 [[ 22  19  16  11   7   7   5   3   2   1]
 [ 31  29  23  20  19  17  13   9   5   2]
 [ 53  47  43  41  37  24  17  11   9   2]
 [ 73  71  67  61  59  23  17  13  10   9]
 [101  97  89  83  79   9   9   8   7   1]]
